"error-stage1:Error communicating with OpenAI: HTTPSConnectionPool(host='chatie.deno.dev', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')))"
http://sha1.sme.zscalertwo.net:10938
openai.verify_ssl_certs = False
https://closeai.deno.dev/
# curl -x http://sha1.sme.zscalertwo.net:10938 https://chatie.deno.dev
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
(liuqiang)
